### ISSUE TITLE
Error while converting

### ISSUE THREAD

**Issue by strngronearth** [slgobinath/pcap-processor#1]
I try to use your tools to convert CICIDS 2017 dataset to CSV file like KDD 99. But when I run `python -m pcap_processor --map protocol --sink csv Wednesday-WorkingHours.pcap` it returns to error ModuleNotFoundError: No module named 'pcap_processor.grpc'. Please tell me the solution. Thank you

**Comment by slgobinath** [comment]
Hi,
Did you install the dependencies using `sudo pip3 install -r requirements.txt`?
If so, please ensure that you are using Python 3 to run pcap_processor. If this doesn't help, please let me know.

**Comment by strngronearth** [comment]
Yes, all the dependencies already satisfied. Anyway, I'm using windows and I installed it with this command `pip install git+https://github.com/slgobinath/pcap-processor.git`. Is it possible to run in windows? If so, please let me know how to set it up. Thank you

**Comment by slgobinath** [comment]
Hi,
I have added the missing `__init__.py` into the grpc folder. Please clone the repo again and check if it works.

I recommend running this program locally since you may need to modify the script based on your requirement.

**Comment by strngronearth** [comment]
Thanks dude, you saved me. It works perfectly

**Comment by slgobinath** [comment]
Thank you for updating the status.
Please cite my paper if you are using this tool for your research:
```
Loganathan, G., Samarabandu, J., & Wang, X. (2018). Sequence to Sequence Pattern Learning Algorithm for Real-time Anomaly Detection in Network Traffic. In 2018 IEEE Canadian Conference on Electrical & Computer Engineering (CCECE) (CCECE 2018). Quebec City, Canada.
```
